### ISSUE TITLE
Any Guide or Documentation how could I load the kext?

### ISSUE THREAD

**Issue by ghost** [AppleIntelWifi/adapter#47]
I find it very difficult to find the guide to load the kext . I am not that technically informed in the hackintosh community (Mostly Linux and WIndows poweruser) so It would be good to make a word or two about installation of the kext. script command would be even nicer. That will  surely help with installing the kext on more hackintoshes and thus more logs and more issues are found the better it would be to shove some light into those areas.
BTW could someone point out how do I install the kext.

**Comment by ghost** [comment]
Ok so found that there are some shell scripts :D but where does the script installs the KEXT?

**Comment by yllwfsh** [comment]
@snajdovski At the moment you shouldn't permanently install the kext, that's why there's no guide. If you want to load the kext temporarily to test, download it [here](https://intelwifi.0xcc.pw/kexts/AppleIntelWifiV2.kext.release.zip), unpack it, then run the following commands in Terminal:

```
cd Downloads/AppleIntelWifiV2.kext.release
sudo chown -R root:wheel AppleIntelWifiAdapterV2.kext
sudo chmod -R 755 AppleIntelWifiAdapterV2.kext
sudo kextload -v AppleIntelWifiAdapterV2.kext
```

At the moment the only thing the driver does is scan network names, if anything at all. No network connections can be made. If you want to help, see https://github.com/AppleIntelWifi/device-logs

**Comment by ghost** [comment]
Thanks, I will try it out later and dump some logs
